ASSEMBLY_AI_API_KEY = "key"
WHISPER_API_KEY = "sk-key"
OPENAI_API_KEY = "sk-key"
GOOGLE_SHEETS_CREDENTIALS = "pitchpal/credentials.json"
EMAIL_ADDRESS = ""
EMAIL_PASSWORD = ""
SPREADSHEET_ID = "pitchpal"
sheet_range = "Sheet1"
